# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=300)),
                ('phone', models.PositiveIntegerField(default='1')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of ride')),
                ('time', models.CharField(max_length=200)),
            ],
        ),
    ]
