# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianStockIdeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='def', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NSEIndiaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nse', max_length=100)),
                ('date1', models.DateField(verbose_name='NSE Date1')),
                ('date2', models.DateField(verbose_name='NSE Date2')),
                ('date3', models.DateField(verbose_name='NSE Date3')),
                ('date4', models.DateField(verbose_name='NSE Date4')),
                ('date5', models.DateField(verbose_name='NSE Date5')),
                ('nse_url', models.URLField(default='https://www.nseindia.com/content/historical/EQUITIES/')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='screener', max_length=200)),
                ('login_username', models.CharField(default='gittopaul2@gmail.com', max_length=200)),
                ('login_password', models.CharField(default='a12345', max_length=200)),
                ('login_url', models.URLField(default='https://www.screener.in/login/')),
                ('api_url', models.URLField(default='https://www.screener.in/api/screens/query/?query=')),
                ('query', models.TextField(default='Current+ratio+%3E+1.2+AND%0D%0AEPS+%3E+EPS+last+year+AND%0D%0ASales+last+year+%3E+Sales+preceding+year+AND%0D%0ANet+Profit+last+year+%3E+Net+Profit+preceding+year+AND%0D%0AMarket+Capitalization+%3E+5+AND%0D%0ANet+Profit++%3E+10+AND%0D%0ANet+Profit+last+year+%3E+5+AND%0D%0Acurrenttohigh+%3C+81', max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
