# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0002_indianstockideas_nseindiadata_screenerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianStockIdeasAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='Run NSE', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='IndianStockIdeas',
        ),
    ]
