# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0003_auto_20170301_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NSEIndiaData',
            new_name='NSESettings',
        ),
        migrations.RenameModel(
            old_name='ScreenerData',
            new_name='ScreenerSettings',
        ),
        migrations.AlterField(
            model_name='indianstockideasaction',
            name='action',
            field=models.CharField(choices=[('Run NSE', 'Run NSE'), ('Run Screener', 'Run Screener'), ('Fetch Data', 'Fetch Data'), ('Run MoneyControl', 'Run MoneyControl')], default='Run NSE', max_length=50),
        ),
    ]
