# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0004_auto_20170301_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NSESettings',
            new_name='NSESetting',
        ),
        migrations.RenameModel(
            old_name='ScreenerSettings',
            new_name='ScreenerSetting',
        ),
    ]
