# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0005_auto_20170301_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('open', models.CharField(blank=True, max_length=100, null=True)),
                ('high', models.CharField(blank=True, max_length=100, null=True)),
                ('low', models.CharField(blank=True, max_length=100, null=True)),
                ('close', models.CharField(blank=True, max_length=100, null=True)),
                ('last', models.CharField(blank=True, max_length=100, null=True)),
                ('prevclose', models.CharField(blank=True, max_length=100, null=True)),
                ('tottrdqty', models.CharField(blank=True, max_length=100, null=True)),
                ('tottrdval', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('totaltrades', models.CharField(blank=True, max_length=100, null=True)),
                ('isin', models.CharField(blank=True, max_length=100, null=True)),
                ('current_price', models.CharField(blank=True, max_length=100, null=True)),
                ('price_to_earning', models.CharField(blank=True, max_length=100, null=True)),
                ('market_capitalization', models.CharField(blank=True, max_length=100, null=True)),
                ('yoy_quarterly_profit_growth', models.CharField(blank=True, max_length=100, null=True)),
                ('yoy_quarterly_sales_growth', models.CharField(blank=True, max_length=100, null=True)),
                ('net_profit', models.CharField(blank=True, max_length=100, null=True)),
                ('profit_growth_3years', models.CharField(blank=True, max_length=100, null=True)),
                ('profit_growth_5years', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_growth_5years', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_growth_3years', models.CharField(blank=True, max_length=100, null=True)),
                ('ctohigh', models.CharField(blank=True, max_length=100, null=True)),
                ('ftw_index', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_from_operations_last_year', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_from_operations_preceding_year', models.CharField(blank=True, max_length=100, null=True)),
                ('executed_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('current_price', models.CharField(blank=True, max_length=100, null=True)),
                ('price_to_earning', models.CharField(blank=True, max_length=100, null=True)),
                ('market_capitalization', models.CharField(blank=True, max_length=100, null=True)),
                ('yoy_quarterly_profit_growth', models.CharField(blank=True, max_length=100, null=True)),
                ('yoy_quarterly_sales_growth', models.CharField(blank=True, max_length=100, null=True)),
                ('net_profit', models.CharField(blank=True, max_length=100, null=True)),
                ('profit_growth_3years', models.CharField(blank=True, max_length=100, null=True)),
                ('profit_growth_5years', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_growth_5years', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_growth_3years', models.CharField(blank=True, max_length=100, null=True)),
                ('ctohigh', models.CharField(blank=True, max_length=100, null=True)),
                ('ftw_index', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_from_operations_last_year', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_from_operations_preceding_year', models.CharField(blank=True, max_length=100, null=True)),
                ('executed_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='indianstockideasaction',
            name='executed_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nsesetting',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='screenersetting',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
