# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0007_auto_20170301_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsesetting',
            name='date6',
            field=models.DateField(default='2016-08-08', verbose_name='NSE Date6'),
            preserve_default=False,
        ),
    ]
