# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0012_screenerdata_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenerdata',
            name='company_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
