# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0013_auto_20170402_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='NseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('open', models.CharField(blank=True, max_length=100, null=True)),
                ('high', models.CharField(blank=True, max_length=100, null=True)),
                ('low', models.CharField(blank=True, max_length=100, null=True)),
                ('close', models.CharField(blank=True, max_length=100, null=True)),
                ('last', models.CharField(blank=True, max_length=100, null=True)),
                ('prevclose', models.CharField(blank=True, max_length=100, null=True)),
                ('tottrdqty', models.CharField(blank=True, max_length=100, null=True)),
                ('tottrdval', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('totaltrades', models.CharField(blank=True, max_length=100, null=True)),
                ('isin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='screenerdata',
            name='company_url',
        ),
        migrations.AddField(
            model_name='featuredstock',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
