# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0015_indianstockideasaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsesetting',
            name='formula',
            field=models.TextField(default='f1 = (dc1*1.2)<(dc2);f2 = (dc1*1.2)<(dc3);f3 = (dc1*1.2)<(dc4);f4 = (dc4*0.8)>(dc5);f5 = (dc4*0.9)>(dc6);f6 = (dc1*0.51)<(dc6);formula = f1 and f2 and f3 and f4 and f5 and f6', max_length=500),
        ),
    ]
