# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0019_auto_20170702_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('current_price', models.CharField(blank=True, max_length=100, null=True)),
                ('price_to_earning', models.CharField(blank=True, max_length=100, null=True)),
                ('market_capitalization', models.CharField(blank=True, max_length=100, null=True)),
                ('yoy_quarterly_profit_growth', models.CharField(blank=True, max_length=100, null=True)),
                ('yoy_quarterly_sales_growth', models.CharField(blank=True, max_length=100, null=True)),
                ('net_profit', models.CharField(blank=True, max_length=100, null=True)),
                ('profit_growth_3years', models.CharField(blank=True, max_length=100, null=True)),
                ('profit_growth_5years', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_growth_5years', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_growth_3years', models.CharField(blank=True, max_length=100, null=True)),
                ('ctohigh', models.CharField(blank=True, max_length=100, null=True)),
                ('ctolow', models.CharField(blank=True, max_length=100, null=True)),
                ('ftw_index', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_from_operations_last_year', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_from_operations_preceding_year', models.CharField(blank=True, max_length=100, null=True)),
                ('quarter_mf', models.CharField(blank=True, max_length=150, null=True)),
                ('quarter_1_mf', models.CharField(blank=True, max_length=150, null=True)),
                ('quarter_2_mf', models.CharField(blank=True, max_length=150, null=True)),
                ('quarter_3_mf', models.CharField(blank=True, max_length=150, null=True)),
                ('quarter_4_mf', models.CharField(blank=True, max_length=150, null=True)),
                ('executed_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
