# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0020_mutualfundholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredstock',
            name='mf_flag',
            field=models.BooleanField(default=False),
        ),
    ]
