# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0021_featuredstock_mf_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredstock',
            name='quarter_1_mf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='featuredstock',
            name='quarter_2_mf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='featuredstock',
            name='quarter_3_mf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='featuredstock',
            name='quarter_4_mf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='featuredstock',
            name='quarter_mf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
