# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0026_exceldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredstock',
            name='chartlink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indianstockideasaction',
            name='action',
            field=models.CharField(choices=[('Run NSE', 'Run NSE'), ('Run Screener', 'Run Screener'), ('Fetch Data', 'Fetch Data'), ('Run MoneyControl', 'Run MoneyControl'), ('Run MoneyControl MutualFund', 'Run MoneyControl MutualFund'), ('Run Chartlink', 'Run Chartlink')], default='Run NSE', max_length=50),
        ),
    ]
