# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0027_auto_20180114_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenersetting',
            name='chartlink_rule',
            field=models.TextField(default='{cash} ( close < ema(close,200) )', max_length=500),
        ),
    ]
