# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianstockideas', '0028_screenersetting_chartlink_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredstock',
            name='five_yr_bullish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='featuredstock',
            name='two_yr_bullish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='featuredstock',
            name='value_buy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
